language: python

python:
  - "2.7"

env:
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18

branches:
    only:
        - master

install: pip install --quiet tox

# command to run tests
script: tox

after_script:
    - if [ $TOXENV == "py27-django18" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
